"""Mosaic GraphQL transport layer (optional ``graphql`` extra).

Autogenerates a GraphQL schema — object types, enums, relationship
fields, queries, and mutations — for any Mosaic deployment by rendering
the shared LinkML type model (:mod:`mosaic.core.schema_typing`, issue
#47). Like the REST transport (``mosaic.serve``), this layer is a THIN
wrapper: every resolver delegates to the Core SDK (``MosaicClient``); no
business logic lives here.

The heavy lifting depends on ``strawberry-graphql``, which ships in the
optional ``graphql`` extra. Public entry points below import lazily and
fail with an actionable message when the extra is not installed.

Public API:

- :func:`build_graphql_schema` — ``SchemaRegistry`` → ``strawberry.Schema``
- :func:`create_graphql_router` — ``MosaicClient`` → FastAPI-mountable router
- :func:`graphql_available` — feature probe for callers (CLI, serve)
- :data:`DEFAULT_MAX_QUERY_DEPTH` — default query-depth limit
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from mosaic.core.client import MosaicClient
    from mosaic.linkml_bridge import SchemaRegistry

GRAPHQL_EXTRA_HINT = (
    "The GraphQL transport requires the optional 'graphql' extra. "
    "Install it with: pip install 'datahelix-mosaic[graphql]'"
)

#: Default maximum GraphQL query depth (hardening against deeply nested
#: relationship-traversal queries). Override per mount via
#: ``create_graphql_router(..., max_query_depth=N)``.
DEFAULT_MAX_QUERY_DEPTH = 10

__all__ = [
    "DEFAULT_MAX_QUERY_DEPTH",
    "GRAPHQL_EXTRA_HINT",
    "build_graphql_schema",
    "create_graphql_router",
    "graphql_available",
]


def graphql_available() -> bool:
    """Return True when the ``graphql`` extra (strawberry) is importable."""
    try:
        import strawberry  # noqa: F401
    except ImportError:
        return False
    return True


def _require_strawberry() -> None:
    """Raise a clear ImportError when strawberry-graphql is missing."""
    try:
        import strawberry  # noqa: F401
    except ImportError as exc:
        raise ImportError(GRAPHQL_EXTRA_HINT) from exc


def build_graphql_schema(
    registry: "SchemaRegistry",
    max_query_depth: int = DEFAULT_MAX_QUERY_DEPTH,
) -> Any:
    """Generate a ``strawberry.Schema`` from a merged LinkML schema.

    Renders the shared type model (``mosaic.core.schema_typing``) for
    every exposed entity class into object types, page types,
    create/update input types, enums, queries, and mutations. See
    :mod:`mosaic.graphql.schema_builder` for the rendering rules.

    Raises:
        ImportError: If the ``graphql`` extra is not installed.
    """
    _require_strawberry()
    from mosaic.graphql.resolvers import build_graphql_schema as _build

    return _build(registry, max_query_depth=max_query_depth)


def create_graphql_router(
    hippo_client: "MosaicClient",
    path: str = "",
    graphiql: bool = True,
    auth_required: bool = True,
    max_query_depth: int = DEFAULT_MAX_QUERY_DEPTH,
) -> Any:
    """Create a FastAPI-mountable GraphQL router for ``hippo_client``.

    The router serves the autogenerated schema for the client's
    ``SchemaRegistry`` and exposes GraphiQL when ``graphiql`` is True.
    At request time resolvers use ``app.state.hippo_client`` (the same
    client the REST routers use); ``hippo_client`` is the construction-
    time source of the schema registry and the fallback client.

    Raises:
        ImportError: If the ``graphql`` extra is not installed.
        mosaic.core.exceptions.ConfigError: If the client has no registry.
    """
    _require_strawberry()
    from mosaic.graphql.router import create_graphql_router as _create

    return _create(
        hippo_client,
        path=path,
        graphiql=graphiql,
        auth_required=auth_required,
        max_query_depth=max_query_depth,
    )
