"""Mosaic Serve module - REST API transport layer."""

from mosaic.api.factory import create_app
from mosaic.core.client import MosaicClient

from mosaic.serve.routers import (
    availability,
    drs,
    entity,
    external_id,
    health,
    history,
    ingest,
    relationship,
    schema,
    search,
    supersede,
    xref,
)

__all__ = [
    "create_app",
    "MosaicClient",
    "availability",
    "drs",
    "entity",
    "external_id",
    "health",
    "history",
    "ingest",
    "relationship",
    "schema",
    "search",
    "supersede",
    "xref",
]


def create_default_app(
    hippo_client: MosaicClient | None = None,
    graphql: bool = False,
    graphql_max_query_depth: int | None = None,
):
    """Create the default Mosaic API application with all routers.

    Args:
        hippo_client: Optional MosaicClient instance.
        graphql: Mount the autogenerated GraphQL transport at ``/graphql``
            (requires the optional ``graphql`` extra and a schema-backed
            ``hippo_client``). The GraphQL resolvers read the same
            ``app.state.hippo_client`` the REST routers use.
        graphql_max_query_depth: Optional override for the GraphQL
            query-depth limit (defaults to
            ``mosaic.graphql.DEFAULT_MAX_QUERY_DEPTH``).

    Returns:
        Configured FastAPI application.

    Raises:
        ImportError: If ``graphql=True`` and the ``graphql`` extra is
            not installed (message includes the install hint).
        mosaic.core.exceptions.ConfigError: If ``graphql=True`` and the
            client carries no SchemaRegistry.
    """
    routers = [
        health.router,
        entity.router,
        ingest.router,
        search.router,
        history.router,
        availability.router,
        supersede.router,
        relationship.router,
        external_id.router,
        xref.router,
        schema.router,
        drs.router,
    ]

    app = create_app(routers=routers, hippo_client=hippo_client)

    if graphql:
        # Lazy import — `mosaic.graphql` raises a clear ImportError with
        # the `pip install 'datahelix-mosaic[graphql]'` hint when strawberry is
        # missing; REST-only deployments never pay the import cost.
        from mosaic.graphql import DEFAULT_MAX_QUERY_DEPTH, create_graphql_router

        graphql_router = create_graphql_router(
            hippo_client or MosaicClient(),
            max_query_depth=(
                graphql_max_query_depth
                if graphql_max_query_depth is not None
                else DEFAULT_MAX_QUERY_DEPTH
            ),
        )
        app.include_router(graphql_router, prefix="/graphql")

    return app


def create_app_from_env():
    """Zero-argument app factory for uvicorn's import-string reload/workers mode.

    ``uvicorn --reload``/``--workers`` re-imports the app in a fresh
    subprocess, so it cannot be handed the CLI's already-built app object —
    it needs an import-string target it can import itself (issue #171).
    Config is threaded through the environment (the ``MOSAIC_*`` convention
    in ``mosaic.config.env``) so the subprocess rebuilds the same deployment
    ``mosaic serve`` resolved: reads ``MOSAIC_CONFIG`` (a config path, or
    unset to auto-detect one in the cwd — same as ``mosaic serve`` with no
    ``--config``), ``MOSAIC_SERVE_GRAPHQL`` (``"1"`` to mount GraphQL), and
    ``MOSAIC_SERVE_GRAPHQL_MAX_DEPTH`` (optional integer override).
    """
    from mosaic.config.env import get_env
    from mosaic.core.factory import (
        create_client,
        create_client_from_config,
        load_config_autodetect,
    )

    cfg = load_config_autodetect(get_env("CONFIG"))
    client = create_client_from_config(cfg) if cfg is not None else create_client()

    max_depth_raw = get_env("SERVE_GRAPHQL_MAX_DEPTH")
    return create_default_app(
        client,
        graphql=get_env("SERVE_GRAPHQL") == "1",
        graphql_max_query_depth=int(max_depth_raw) if max_depth_raw else None,
    )
