"""Validation module for Mosaic.

Provides core validation types and abstract base classes for write operation validation.
"""

from mosaic.core.validation.validators import (
    BatchValidationResult,
    BatchWriteResult,
    ValidationResult,
    WriteOperation,
    WriteValidator,
    ValidatorPipeline,
    ValidatorRegistry,
)
from mosaic.core.validation.schema_validator import (
    SchemaValidationConfig,
    SchemaValidator,
)
from mosaic.core.validation.presets import (
    PresetConfig,
    PresetValidator,
    PresetRegistry,
    get_preset_registry,
    ErrorMessageBuilder,
    ReferenceConstraintViolation,
    CountConstraintViolation,
    ImmutableFieldViolation,
    FieldRequiredViolation,
    SelfReferenceViolation,
    REF_CHECK_PRESET,
    COUNT_CONSTRAINT_PRESET,
    IMMUTABLE_FIELD_PRESET,
    FIELD_REQUIRED_IF_PRESET,
    NO_SELF_REF_PRESET,
    RefCheckPreset,
    CountConstraintPreset,
    ImmutableFieldPreset,
    FieldRequiredIfPreset,
    NoSelfRefPreset,
    register_presets,
)
from mosaic.core.validation.executor import (
    ValidatorExecutor,
    ValidatorContext,
    ExecutorConfig,
    ValidatorConfig,
    ValidationTimeoutError,
    FeatureNotAvailableError,
    ValidatorExecutionError,
    ValidatorConfigError,
    create_executor,
)
from mosaic.core.validation.loader import (
    load_validators,
    expand_nested_rules,
    create_executor_from_yaml,
)

__all__ = [
    "BatchValidationResult",
    "BatchWriteResult",
    "ValidationResult",
    "WriteOperation",
    "WriteValidator",
    "ValidatorPipeline",
    "ValidatorRegistry",
    "SchemaValidator",
    "SchemaValidationConfig",
    "PresetConfig",
    "PresetValidator",
    "PresetRegistry",
    "get_preset_registry",
    "ErrorMessageBuilder",
    "ReferenceConstraintViolation",
    "CountConstraintViolation",
    "ImmutableFieldViolation",
    "FieldRequiredViolation",
    "SelfReferenceViolation",
    "REF_CHECK_PRESET",
    "COUNT_CONSTRAINT_PRESET",
    "IMMUTABLE_FIELD_PRESET",
    "FIELD_REQUIRED_IF_PRESET",
    "NO_SELF_REF_PRESET",
    "RefCheckPreset",
    "CountConstraintPreset",
    "ImmutableFieldPreset",
    "FieldRequiredIfPreset",
    "NoSelfRefPreset",
    "register_presets",
    "ValidatorExecutor",
    "ValidatorContext",
    "ExecutorConfig",
    "ValidatorConfig",
    "ValidationTimeoutError",
    "FeatureNotAvailableError",
    "ValidatorExecutionError",
    "ValidatorConfigError",
    "create_executor",
    "load_validators",
    "expand_nested_rules",
    "create_executor_from_yaml",
]
